/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary': '#99f7ff',
        'primary-fixed-dim': '#718bff',
        'surface-variant': '#192540',
        'on-tertiary-fixed': '#004145',
        'on-error': '#490006',
        'tertiary-fixed-dim': '#00e2ee',
        'surface-dim': '#060e20',
        'outline-variant': '#40485d',
        'surface-container-highest': '#192540',
        'surface-tint': '#97a9ff',
        'tertiary-container': '#00f1fe',
        'primary-fixed': '#859aff',
        'surface-container-lowest': '#000000',
        'inverse-on-surface': '#4d556b',
        'on-primary-container': '#001867',
        'on-secondary': '#33005b',
        'on-primary': '#002283',
        'on-primary-fixed-variant': '#00207e',
        'on-secondary-fixed-variant': '#7511c3',
        'secondary-fixed-dim': '#dbb4ff',
        'on-tertiary-container': '#00555a',
        'surface-container': '#0f1930',
        'on-tertiary-fixed-variant': '#006065',
        'background': '#060e20',
        'primary-container': '#859aff',
        'surface-container-low': '#091328',
        'surface-container-high': '#141f38',
        'outline': '#6d758c',
        'secondary-dim': '#9c48ea',
        'primary': '#97a9ff',
        'on-surface-variant': '#a3aac4',
        'secondary-fixed': '#e5c6ff',
        'surface': '#060e20',
        'inverse-primary': '#134af1',
        'tertiary-dim': '#00e2ee',
        'on-surface': '#dee5ff',
        'tertiary-fixed': '#00f1fe',
        'on-background': '#dee5ff',
        'secondary-container': '#6f00be',
        'primary-dim': '#3e65ff',
        'error-dim': '#d7383b',
        'surface-bright': '#1f2b49',
        'secondary': '#c180ff',
        'on-error-container': '#ffa8a3',
        'inverse-surface': '#faf8ff',
        'error-container': '#9f0519',
        'on-primary-fixed': '#000000',
        'on-tertiary': '#005f64',
        'on-secondary-fixed': '#4f0089',
        'error': '#ff716c',
        'on-secondary-container': '#e9cdff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
