/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary': '#64748b',
        'primary-fixed-dim': '#475569',
        'surface-variant': '#f1f5f9',
        'on-tertiary-fixed': '#ffffff',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#475569',
        'surface-dim': '#f8fafc',
        'outline-variant': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'surface-tint': '#0f172a',
        'tertiary-container': '#e2e8f0',
        'primary-fixed': '#334155',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f8fafc',
        'on-primary-container': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#e2e8f0',
        'on-secondary-fixed-variant': '#334155',
        'secondary-fixed-dim': '#64748b',
        'on-tertiary-container': '#1e293b',
        'surface-container': '#f1f5f9',
        'on-tertiary-fixed-variant': '#475569',
        'background': '#ffffff',
        'primary-container': '#e2e8f0',
        'surface-container-low': '#f8fafc',
        'surface-container-high': '#e2e8f0',
        'outline': '#94a3b8',
        'secondary-dim': '#334155',
        'primary': '#0f172a',
        'on-surface-variant': '#64748b',
        'secondary-fixed': '#cbd5e1',
        'surface': '#ffffff',
        'inverse-primary': '#f8fafc',
        'tertiary-dim': '#475569',
        'on-surface': '#0f172a',
        'tertiary-fixed': '#e2e8f0',
        'on-background': '#0f172a',
        'secondary-container': '#e2e8f0',
        'primary-dim': '#1e293b',
        'error-dim': '#dc2626',
        'surface-bright': '#ffffff',
        'secondary': '#475569',
        'on-error-container': '#dc2626',
        'inverse-surface': '#0f172a',
        'error-container': '#fee2e2',
        'on-primary-fixed': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#0f172a',
        'error': '#dc2626',
        'on-secondary-container': '#0f172a',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
